(define (compose f g)
  (lambda (x) (f (g x))))

(define (repeated f n)
  (if (= n 0)
    (lambda (x) x)
    (compose f (repeated f (- n 1)))))

(display ((repeated square 1) 2))
(newline)
(display ((repeated square 2) 2))
(newline)
(display ((repeated square 2) 5))
(newline)
(display ((repeated square 3) 2))
(newline)
