(define (elem-xy x y)
  (if (or (= x 0) (= x y))
    1
    (+ (elem-xy (- x 1) (- y 1))
       (elem-xy x (- y 1)))))

(display (elem-xy 0 0))
(newline)
(display (elem-xy 0 1))
(display " ")
(display (elem-xy 1 1))
(newline)
(display (elem-xy 0 2))
(display " ")
(display (elem-xy 1 2))
(display " ")
(display (elem-xy 2 2))
(newline)
(display (elem-xy 0 3))
(display " ")
(display (elem-xy 1 3))
(display " ")
(display (elem-xy 2 3))
(display " ")
(display (elem-xy 3 3))
(newline)
(display (elem-xy 0 4))
(display " ")
(display (elem-xy 1 4))
(display " ")
(display (elem-xy 2 4))
(display " ")
(display (elem-xy 3 4))
(display " ")
(display (elem-xy 4 4))
(newline)
