(define (make-monitored f)
  (define call-count 0)
  (define (mf x)
    (cond ((eq? x 'how-many-calls?) call-count)
          ((eq? x 'reset-count) (set! call-count 0))
          (else
            (set! call-count (+ 1 call-count))
            (f x))))
  mf)

(define s (make-monitored sqrt))
(display (s 100))
(newline)
(display (s 'how-many-calls?))
(newline)
(display (s 25))
(newline)
(display (s 'how-many-calls?))
(newline)
(display (s 'reset-count))
(newline)
(display (s 'how-many-calls?))
(newline)
