(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define wrong-password-count 0)
  (define (wrong-password . args)
    (set! wrong-password-count (+ 1 wrong-password-count))
    (if (> wrong-password-count 7) (call-the-cops))
    "Incorrect password")
  (define (dispatch p m)
    (cond ((not (eq? p password)) wrong-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define (call-the-cops) (display "the cops have been called\n"))

(define acc (make-account 100 'secret-password))
(display ((acc 'secret-password 'withdraw) 40))
(newline)
(display ((acc '0 'deposit) 50))
(newline)
(display ((acc '1 'deposit) 50))
(newline)
(display ((acc '2 'deposit) 50))
(newline)
(display ((acc '3 'deposit) 50))
(newline)
(display ((acc '4 'deposit) 50))
(newline)
(display ((acc '5 'deposit) 50))
(newline)
(display ((acc '6 'deposit) 50))
(newline)
(display ((acc '7 'deposit) 50))
(newline)
