(define (make-account balance password)
  (define pwd-list (list password))
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (add-password)
    (lambda (new-pwd) (set! pwd-list (cons new-pwd pwd-list))))
  (define (wrong-password . args) "Incorrect password")
  (define (dispatch p m)
    (cond ((not (member p pwd-list)) wrong-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          ((eq? m 'add-password) add-password)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define peter-acc (make-account 100 'open-sesame))
(display ((peter-acc 'open-sesame 'withdraw) 40))
(newline)
(display ((peter-acc 'rosebud 'deposit) 50))
(newline)

(define (make-joint acc password new-password)
  ((acc 'add-password password) new-password)
  acc)

(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))
(display ((paul-acc 'open-sesame 'withdraw) 40))
(newline)
(display ((paul-acc 'rosebud 'deposit) 50))
(newline)

(display ((paul-acc 'open-sesame 'withdraw) 20))
(newline)
