(define (add-rat x y)
  (make-rat (+ (* (numer x) (denom y))
               (* (numer y) (denom x)))
            (* (denom x) (denom y))))
(define (sub-rat x y)
  (make-rat (- (* (numer x) (denom y))
               (* (numer y) (denom x)))
            (* (denom x) (denom y))))
(define (mul-rat x y)
  (make-rat (* (numer x) (numer y))
            (* (denom x) (denom y))))
(define (equal-rat? x y)
  (= (* (numer x) (denom y))
     (* (numer y) (denom x))))

(define x (cons 1 2))
(display (car x))
(newline)
(display (cdr x))
(newline)

(define x (cons 1 2))
(define y (cons 3 4))
(define z (cons x y))
(display (car (car z)))
(newline)
(display (car (cdr z)))
(newline)

(define (make-rat n d) (cons n d))
(define (numer x) (car x))
(define (denom x) (cdr x))

(define (print-rat x)
  (display (numer x))
  (display "/")
  (display (denom x)))

(define one-half (make-rat 1 2))
(print-rat one-half)
(newline)

(define one-third (make-rat 1 3))
(print-rat (add-rat one-half one-third))
(newline)

(print-rat (mul-rat one-half one-third))
(newline)

(print-rat (add-rat one-third one-third))
(newline)

(define (make-rat n d)
  (let ((g (gcd n d)))
    (cons (/ n g) (/ d g))))

(print-rat (add-rat one-third one-third))
(newline)
