(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
                 (+ (upper-bound x) (upper-bound y))))

(define (mul-interval x y)
  (let ((p1 (* (lower-bound x) (lower-bound y)))
        (p2 (* (lower-bound x) (upper-bound y)))
        (p3 (* (upper-bound x) (lower-bound y)))
        (p4 (* (upper-bound x) (upper-bound y))))
    (make-interval (min p1 p2 p3 p4)
                   (max p1 p2 p3 p4))))

(define (div-interval x y)
  (mul-interval x
                (make-interval (/ 1.0 (upper-bound y))
                               (/ 1.0 (lower-bound y)))))

(define (make-interval a b) (cons a b))
(define (lower-bound x) (car x))
(define (upper-bound x) (cdr x))

(define (print-interval i)
  (display "(")
  (display (lower-bound i))
  (display ",")
  (display (upper-bound i))
  (display ")"))

(define (sub-interval x y)
  (make-interval (- (lower-bound x) (lower-bound y))
                 (- (upper-bound x) (upper-bound y))))

(define i1 (make-interval 6.12 7.48))
(define i2 (make-interval 4.465 4.935))

(print-interval (add-interval i1 i2))
(newline)
(print-interval (sub-interval i1 i2))
(newline)
(print-interval (mul-interval i1 i2))
(newline)
(print-interval (div-interval i1 i2))
(newline)

(define (make-center-width c w)
  (make-interval (- c w) (+ c w)))
(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2))

(define i1 (make-center-width 6.8 0.68))
(define i2 (make-center-width 4.7 0.235))

(newline)
(print-interval (add-interval i1 i2))
(newline)
(print-interval (sub-interval i1 i2))
(newline)
(print-interval (mul-interval i1 i2))
(newline)
(print-interval (div-interval i1 i2))
(newline)

(define (make-center-percent c p)
  (make-interval (* c (- 1 p)) (* c (+ 1 p))))
(define (percent i)
  (/ (width i) (center i)))

(define i1 (make-center-percent 6.8 0.1))
(define i2 (make-center-percent 4.7 0.05))

(newline)
(print-interval (add-interval i1 i2))
(newline)
(print-interval (sub-interval i1 i2))
(newline)
(print-interval (mul-interval i1 i2))
(newline)
(print-interval (div-interval i1 i2))
(newline)
